version: "3.4"

volumes:
  mysql: ~

services:
  php:
    restart: "no"
    build:
      context: "./"
      dockerfile: "./docker/php/Dockerfile"
    volumes:
      - ".:/app"
    command: "php -S 0.0.0.0:80 -t public -c .docker/php/php.ini"
    ports:
      - "80:80"
    links:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:rootpassword@mysql:3306/main"
      APP_ENV: "test"
      PHP_IDE_CONFIG: "serverName=Behat"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    healthcheck:
      test: "mysqladmin ping -h localhost -P 3306 -u $${MYSQL_USER} -p$${MYSQL_PASSWORD}"
      interval: 2s
      timeout: 5s
      retries: 15
