imports:
    - { resource: "../src/Behat/Resources/config/services.yml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
